name: Build & Deploy

on:
  push:
    branches:
      - main
      
env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Updated to the latest v4 version

      - name: Setup Node
        uses: actions/setup-node@v4  # Updated to the latest v4 version
        with:
          node-version: 20  # Specify Node.js 20

      - name: Install dependencies
        uses: bahmutov/npm-install@v1  # Using the latest stable version

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3  # Updated to the latest v3 version
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3  # Updated to the latest v3 version
        with:
          name: production-files
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Using the latest stable version
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build
