name: Build & Deploy

on:
  push:
    branches:
      - main
      
env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        # Update to the latest version compatible with Node.js 20
        uses: actions/checkout@v3  # v3 is the latest and recommended

      - name: Setup Node
        # Update to the latest version and set Node.js to 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify Node.js 20

      - name: Install dependencies
        # Update to the latest version of bahmutov/npm-install
        uses: bahmutov/npm-install@v1  # v1 is the latest and stable

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        # Update to the latest version of actions/upload-artifact
        uses: actions/upload-artifact@v3  # v3 is the latest and recommended
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        # Update to the latest version of actions/download-artifact
        uses: actions/download-artifact@v3  # v3 is the latest and recommended
        with:
          name: production-files
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build
